### ISSUE TITLE
StartApp (Integrating Native Ads) can run in the non UI thread?(Android app)

### ISSUE THREAD

**Issue by pengkshu** [StartApp-SDK/StartApp_InApp_SDK_Unity_Example#1]
I found initializing and loading a StartAppNativeAd Object was used too much time.I want to use it in an non UI Thread.But it does't work.Can it run in non UI Thread?

**Comment by StartApp-SDK** [comment]
Hi pengkshu, 
Currently our StartAppNativeAd not suppose to work in Unity project.
Here is the [Unity integration guide](https://github.com/StartApp-SDK/Documentation/wiki/Android-InApp-Unity-Documentation) that explain what ad types exists and how to use them.

**Comment by pengkshu** [comment]
Please forgive for not clearly explaining what i ask.I use it in general android app.I not use it in Unity project.Because the StartApp_InApp_SDK_Example don't have issue.I only ask it in here.

**Comment by StartApp-SDK** [comment]
Hi pengkshu,
Loading native ads is asynchronous, so it wouldn't help loading it in another non UI Thread.
For any other questions please contact support@startapp.com
